export const UPDATE_IS_LOADING_STATUS = "UPDATE_IS_LOADING_STATUS";
export const UPDATE_HEADER_DATA = "UPDATE_HEADER_DATA";
export const UPDATE_FOOTER_DATA = "UPDATE_FOOTER_DATA";
export const UPDATE_INDEX_DATA = "UPDATE_INDEX_DATA";